repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.0.0
  hooks:
  - id: reorder-python-imports
    exclude: ^setup.py
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.1.1
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ["-l 100"]
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies: [
      flake8-docstrings==1.7.0,
      # flake8-global-variables==0.1.2 # Consider adding this
    ]
    args: []
